version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      MONGO_URI: mongodb://mongo:27017/taskmanagement
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
